### ISSUE TITLE
Order of output

### ISSUE THREAD

**Issue by brefan** [browserify/module-deps#104]
When i run the example, the order of the output is reversed compared to the example output in the readme. Generally I'd like to know, if the order is guaranteed in so far, that a dep comes always after (or before in my case) the files which require it.

**Comment by zertosh** [comment]
You can't rely on any order. For any given inputs, the output order will most often be the same, but because pretty much everything in module-deps is async, anything can happen. This is why browserify uses [deps-sort](https://github.com/substack/deps-sort) to ensure that dependencies are ordered consistently for deterministic builds.
